# Generated by Django 5.0.4 on 2024-04-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_name', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('native_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dance',
                'verbose_name_plural': 'Dances',
                'db_table': 'Dance',
                'ordering': ['dance_name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance.dance')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'Artist',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance.artist')),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance.dance')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'db_table': 'Performance',
                'ordering': ['title'],
            },
        ),
    ]
